# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    producer_service:
        class: AppBundle\Services\Producer
        arguments: ["@old_sound_rabbit_mq.api_call_producer", "@logger"]
    consummer_call:
        class: AppBundle\Services\Consumer
        arguments: ["@mrsuh_vk_api", "@doctrine.orm.default_entity_manager", "@logger"]
    user_controller:
        class: AppBundle\Controller\UserController
        arguments: ["@doctrine.orm.default_entity_manager"]